"""OntologyFactory — builds ontology config dicts for tests.

Mirrors the shape consumed by `back.objects.ontology.OntologyService` and
`back.core.w3c.owl.OWLGenerator`. Produces dicts (not pydantic models) so it
plays nice with code paths that round-trip through JSON.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class OntologyFactory:
    """Build ontology config dicts with controlled shape.

    Defaults produce a minimal but coherent Customer/Order ontology.

    Args:
        name: Ontology display name.
        base_uri: Base IRI for class/property URIs.
        classes: Number of classes to generate (or a list of names for explicit control).
        properties: Number of object properties to generate.
        data_properties_per_class: Data properties added to each generated class.
        with_inheritance: If True, every class after the first is a subClassOf the previous.
        with_constraints: If True, include SHACL-style cardinality constraints.
        seed: Deterministic seed for property test reproducibility.
    """

    name: str = "TestOntology"
    base_uri: str = "http://test.org/ontology#"
    classes: int | list[str] = 2
    properties: int = 1
    data_properties_per_class: int = 2
    with_inheritance: bool = False
    with_constraints: bool = False
    seed: int = 0

    @classmethod
    def build(cls, **overrides: Any) -> dict[str, Any]:
        return cls(**overrides)._build()

    def _build(self) -> dict[str, Any]:
        class_names = self._class_names()
        classes = [self._class(name, idx, class_names) for idx, name in enumerate(class_names)]
        properties = self._properties(class_names)
        return {
            "name": self.name,
            "base_uri": self.base_uri,
            "description": f"{self.name} — generated by OntologyFactory",
            "classes": classes,
            "properties": properties,
            "constraints": self._constraints(class_names) if self.with_constraints else [],
            "swrl_rules": [],
            "axioms": [],
            "expressions": [],
        }

    def _class_names(self) -> list[str]:
        if isinstance(self.classes, list):
            return list(self.classes)
        defaults = ["Customer", "Order", "Product", "Address", "Invoice", "LineItem"]
        if self.classes <= len(defaults):
            return defaults[: self.classes]
        # Fall back to numbered names beyond the default pool.
        return defaults + [f"Class{i}" for i in range(len(defaults), self.classes)]

    def _class(self, name: str, idx: int, all_names: list[str]) -> dict[str, Any]:
        parent = ""
        if self.with_inheritance and idx > 0:
            parent = all_names[idx - 1]
        data_props = [
            {
                "name": f"{name.lower()}Attr{i}",
                "localName": f"{name.lower()}Attr{i}",
                "label": f"{name} Attribute {i}",
            }
            for i in range(self.data_properties_per_class)
        ]
        return {
            "uri": f"{self.base_uri}{name}",
            "name": name,
            "label": name,
            "comment": f"A {name.lower()} entity",
            "emoji": "🧩",
            "parent": parent,
            "dataProperties": data_props,
        }

    def _properties(self, class_names: list[str]) -> list[dict[str, Any]]:
        if not class_names or self.properties <= 0:
            return []
        # Build forward edges in a deterministic round-robin between classes.
        props: list[dict[str, Any]] = []
        for i in range(self.properties):
            src = class_names[i % len(class_names)]
            tgt = class_names[(i + 1) % len(class_names)]
            props.append(
                {
                    "uri": f"{self.base_uri}has{tgt}",
                    "name": f"has{tgt}",
                    "label": f"has {tgt}",
                    "comment": f"Links {src} to {tgt}",
                    "type": "ObjectProperty",
                    "domain": src,
                    "range": tgt,
                }
            )
        return props

    def _constraints(self, class_names: list[str]) -> list[dict[str, Any]]:
        # Sensible default: every class has min-1 cardinality on its first data property.
        return [
            {
                "target_class": f"{self.base_uri}{name}",
                "constraint_type": "minCount",
                "value": 1,
                "property": f"{self.base_uri}{name.lower()}Attr0",
            }
            for name in class_names
        ]
